pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                bat 'npm install'
                bat  'npm run dev'
            }
        }
        stage('Deploy') {
            steps {
               bat 'json-server --watch db.json'
            }
        }
    }
}